package com.mats.ponder;
import net.createmod.ponder.api.registration.PonderSceneRegistrationHelper;
import net.createmod.ponder.api.scene.SceneBuilder;
import net.createmod.ponder.api.scene.SceneBuildingUtil;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.world.level.ItemLike;
import net.minecraft.resources.ResourceLocation;
public class AutoScenes {
    private static final String[][] BLOCKS = {
        {"ae2", "paint", "Paint"},
        {"ae2", "crafting_accelerator", "Crafting Co-Processing Unit"},
        {"ae2", "smooth_quartz_stairs", "Smooth Certus Quartz Stairs"},
        {"ae2", "sky_stone_brick_wall", "Sky Stone Brick Wall"},
        {"ae2", "debug_cube_gen", "Dev.CubeGen"},
        {"ae2", "matrix_frame", "Matrix Frame"},
        {"ae2", "not_so_mysterious_cube", "Not So Mysterious Cube"},
        {"ae2", "1k_crafting_storage", "1k Crafting Storage"},
        {"ae2", "quartz_brick_slab", "Certus Quartz Brick Slab"},
        {"ae2", "64k_crafting_storage", "64k Crafting Storage"},
        {"ae2", "light_detector", "Light Detecting Fixture"},
        {"ae2", "quartz_cluster", "Certus Quartz Cluster"},
        {"ae2", "quartz_slab", "Certus Quartz Slab"},
        {"ae2", "small_quartz_bud", "Small Certus Quartz Bud"},
        {"ae2", "flawed_budding_quartz", "Flawed Budding Certus Quartz"},
        {"ae2", "fluix_stairs", "Fluix Stairs"},
        {"ae2", "crafting_unit", "Crafting Unit"},
        {"ae2", "quartz_pillar_stairs", "Certus Quartz Pillar Stairs"},
        {"ae2", "sky_stone_small_brick_stairs", "Sky Stone Small Brick Stairs"},
        {"ae2", "condenser", "Matter Condenser"},
        {"ae2", "dense_energy_cell", "Dense Energy Cell"},
        {"ae2", "quartz_fixture", "Charged Quartz Fixture"},
        {"ae2", "quartz_block", "Certus Quartz Block"},
        {"ae2", "quartz_glass", "Quartz Glass"},
        {"ae2", "chiseled_quartz_block", "Chiseled Certus Quartz Block"},
        {"ae2", "chest", "ME Chest"},
        {"ae2", "sky_stone_stairs", "Sky Stone Stairs"},
        {"ae2", "cell_workbench", "Cell Workbench"},
        {"ae2", "chiseled_quartz_slab", "Chiseled Certus Quartz Slab"},
        {"ae2", "io_port", "ME IO Port"},
        {"ae2", "sky_stone_chest", "Sky Stone Chest"},
        {"ae2", "smooth_quartz_block", "Smooth Certus Quartz Block"},
        {"ae2", "cut_quartz_stairs", "Cut Certus Quartz Stairs"},
        {"ae2", "quartz_brick_wall", "Certus Quartz Brick Wall"},
        {"ae2", "quartz_pillar_slab", "Certus Quartz Pillar Slab"},
        {"ae2", "256k_crafting_storage", "256k Crafting Storage"},
        {"ae2", "flawless_budding_quartz", "Flawless Budding Certus Quartz"},
        {"ae2", "chiseled_quartz_stairs", "Chiseled Certus Quartz Stairs"},
        {"ae2", "quartz_brick_stairs", "Certus Quartz Brick Stairs"},
        {"ae2", "sky_stone_block", "Sky Stone"},
        {"ae2", "energy_cell", "Energy Cell"},
        {"ae2", "sky_stone_brick_slab", "Sky Stone Brick Slab"},
        {"ae2", "crank", "Wooden Crank"},
        {"ae2", "tiny_tnt", "Tiny TNT"},
        {"ae2", "sky_stone_wall", "Sky Stone Wall"},
        {"ae2", "fluix_block", "Fluix Block"},
        {"ae2", "chipped_budding_quartz", "Chipped Budding Certus Quartz"},
        {"ae2", "debug_energy_gen", "Dev.EnergyGen"},
        {"ae2", "fluix_slab", "Fluix Slab"},
        {"ae2", "debug_item_gen", "Dev.ItemGen"},
        {"ae2", "medium_quartz_bud", "Medium Certus Quartz Bud"},
        {"ae2", "sky_stone_brick_stairs", "Sky Stone Brick Stairs"},
        {"ae2", "chiseled_quartz_wall", "Chiseled Certus Quartz Wall"},
        {"ae2", "cut_quartz_block", "Cut Certus Quartz Block"},
        {"ae2", "quartz_vibrant_glass", "Vibrant Quartz Glass"},
        {"ae2", "spatial_io_port", "Spatial IO Port"},
        {"ae2", "cut_quartz_wall", "Cut Certus Quartz Wall"},
        {"ae2", "fluix_wall", "Fluix Wall"},
        {"ae2", "spatial_anchor", "Spatial Anchor"},
        {"ae2", "sky_stone_tank", "Sky Stone Tank"},
        {"ae2", "quartz_stairs", "Certus Quartz Stairs"},
        {"ae2", "damaged_budding_quartz", "Damaged Budding Certus Quartz"},
        {"ae2", "sky_stone_small_brick_wall", "Sky Stone Small Brick Wall"},
        {"ae2", "smooth_quartz_wall", "Smooth Certus Quartz Wall"},
        {"ae2", "debug_phantom_node", "Dev.PhantomNode"},
        {"ae2", "large_quartz_bud", "Large Certus Quartz Bud"},
        {"ae2", "sky_stone_brick", "Sky Stone Brick"},
        {"ae2", "smooth_sky_stone_block", "Sky Stone Block"},
        {"ae2", "smooth_sky_stone_stairs", "Sky Stone Block Stairs"},
        {"ae2", "crafting_monitor", "Crafting Monitor"},
        {"ae2", "cut_quartz_slab", "Cut Certus Quartz Slab"},
        {"ae2", "quartz_pillar", "Certus Quartz Pillar"},
        {"ae2", "smooth_sky_stone_chest", "Sky Stone Block Chest"},
        {"ae2", "creative_energy_cell", "Creative Energy Cell"},
        {"ae2", "crystal_resonance_generator", "Crystal Resonance Generator"},
        {"ae2", "growth_accelerator", "Growth Accelerator"},
        {"ae2", "quartz_pillar_wall", "Certus Quartz Pillar Wall"},
        {"ae2", "sky_stone_small_brick", "Sky Stone Small Brick"},
        {"ae2", "smooth_quartz_slab", "Smooth Certus Quartz Slab"},
        {"ae2", "molecular_assembler", "Molecular Assembler"},
        {"ae2", "16k_crafting_storage", "16k Crafting Storage"},
        {"ae2", "quartz_wall", "Certus Quartz Wall"},
        {"ae2", "spatial_pylon", "Spatial Pylon"},
        {"ae2", "vibration_chamber", "Vibration Chamber"},
        {"ae2", "wireless_access_point", "ME Wireless Access Point"},
        {"ae2", "mysterious_cube", "Mysterious Cube"},
        {"ae2", "smooth_sky_stone_wall", "Sky Stone Block Wall"},
        {"ae2", "sky_stone_small_brick_slab", "Sky Stone Small Brick Slab"},
        {"ae2", "quartz_bricks", "Certus Quartz Bricks"},
        {"ae2", "4k_crafting_storage", "4k Crafting Storage"},
        {"ae2", "interface", "ME Interface"},
        {"ae2", "cable_bus", "AE2 Cable and/or Bus"},
        {"ae2", "quantum_link", "ME Quantum Link Chamber"},
        {"ae2", "sky_stone_slab", "Sky Stone Slab"},
        {"ae2", "smooth_sky_stone_slab", "Sky Stone Block Slab"},
        {"supplementaries", "ash", "Ash"},
        {"supplementaries", "ash_bricks", "Ash Bricks"},
        {"supplementaries", "ash_bricks_slab", "Ash Brick Slab"},
        {"supplementaries", "ash_bricks_stairs", "Ash Brick Stairs"},
        {"supplementaries", "ash_bricks_wall", "Ash Brick Wall"},
        {"supplementaries", "ashen_basalt", "Basalt"},
        {"supplementaries", "awning", "Awning"},
        {"supplementaries", "awning_black", "Black Awning"},
        {"supplementaries", "awning_blue", "Blue Awning"},
        {"supplementaries", "awning_brown", "Brown Awning"},
        {"supplementaries", "awning_cyan", "Cyan Awning"},
        {"supplementaries", "awning_gray", "Gray Awning"},
        {"supplementaries", "awning_green", "Green Awning"},
        {"supplementaries", "awning_light_blue", "Light Blue Awning"},
        {"supplementaries", "awning_light_gray", "Light Gray Awning"},
        {"supplementaries", "awning_lime", "Lime Awning"},
        {"supplementaries", "awning_magenta", "Magenta Awning"},
        {"supplementaries", "awning_orange", "Orange Awning"},
        {"supplementaries", "awning_pink", "Pink Awning"},
        {"supplementaries", "awning_purple", "Purple Awning"},
        {"supplementaries", "awning_red", "Red Awning"},
        {"supplementaries", "awning_white", "White Awning"},
        {"supplementaries", "awning_yellow", "Yellow Awning"},
        {"supplementaries", "bamboo_spikes", "Bamboo Spikes"},
        {"supplementaries", "barnacles", "Barnacles"},
        {"supplementaries", "bellows", "Bellows"},
        {"supplementaries", "blackboard", "Blackboard"},
        {"supplementaries", "blackstone_lamp", "Blackstone Lamp"},
        {"supplementaries", "blackstone_tile", "Blackstone Tiles"},
        {"supplementaries", "blackstone_tile_slab", "Blackstone Tile Slab"},
        {"supplementaries", "blackstone_tile_stairs", "Blackstone Tile Stairs"},
        {"supplementaries", "blackstone_tile_wall", "Blackstone Tile Wall"},
        {"supplementaries", "blaze_rod", "Blaze Rod"},
        {"supplementaries", "book_pile", "Book Pile"},
        {"supplementaries", "book_pile_horizontal", "Book Pile"},
        {"supplementaries", "breeze_rod", "Breeze Rod"},
        {"supplementaries", "bubble_block", "Bubble Block"},
        {"supplementaries", "bunting_black", "Black Bunting"},
        {"supplementaries", "bunting_blue", "Blue Bunting"},
        {"supplementaries", "bunting_brown", "Brown Bunting"},
        {"supplementaries", "bunting_cyan", "Cyan Bunting"},
        {"supplementaries", "bunting_gray", "Gray Bunting"},
        {"supplementaries", "bunting_green", "Green Bunting"},
        {"supplementaries", "bunting_light_blue", "Light Blue Bunting"},
        {"supplementaries", "bunting_light_gray", "Light Gray Bunting"},
        {"supplementaries", "bunting_lime", "Lime Bunting"},
        {"supplementaries", "bunting_magenta", "Magenta Bunting"},
        {"supplementaries", "bunting_orange", "Orange Bunting"},
        {"supplementaries", "bunting_pink", "Pink Bunting"},
        {"supplementaries", "bunting_purple", "Purple Bunting"},
        {"supplementaries", "bunting_red", "Red Bunting"},
        {"supplementaries", "bunting_wall_black", "Black Wall Bunting"},
        {"supplementaries", "bunting_wall_blue", "Blue Wall Bunting"},
        {"supplementaries", "bunting_wall_brown", "Brown Wall Bunting"},
        {"supplementaries", "bunting_wall_cyan", "Cyan Wall Bunting"},
        {"supplementaries", "bunting_wall_gray", "Gray Wall Bunting"},
        {"supplementaries", "bunting_wall_green", "Green Wall Bunting"},
        {"supplementaries", "bunting_wall_light_blue", "Light Blue Wall Bunting"},
        {"supplementaries", "bunting_wall_light_gray", "Light Gray Wall Bunting"},
        {"supplementaries", "bunting_wall_lime", "Lime Wall Bunting"},
        {"supplementaries", "bunting_wall_magenta", "Magenta Wall Bunting"},
        {"supplementaries", "bunting_wall_orange", "Orange Wall Bunting"},
        {"supplementaries", "bunting_wall_pink", "Pink Wall Bunting"},
        {"supplementaries", "bunting_wall_purple", "Purple Wall Bunting"},
        {"supplementaries", "bunting_wall_red", "Red Wall Bunting"},
        {"supplementaries", "bunting_wall_white", "White Wall Bunting"},
        {"supplementaries", "bunting_wall_yellow", "Yellow Wall Bunting"},
        {"supplementaries", "bunting_white", "White Bunting"},
        {"supplementaries", "bunting_yellow", "Yellow Bunting"},
        {"supplementaries", "cage", "Cage"},
        {"supplementaries", "candle_holder", "Candle Holder"},
        {"supplementaries", "candle_holder_black", "Black Candle Holder"},
        {"supplementaries", "candle_holder_blue", "Blue Candle Holder"},
        {"supplementaries", "candle_holder_brown", "Brown Candle Holder"},
        {"supplementaries", "candle_holder_cupric", "Cupric Candle Holder"},
        {"supplementaries", "candle_holder_cyan", "Cyan Candle Holder"},
        {"supplementaries", "candle_holder_ender", "Ender Candle Holder"},
        {"supplementaries", "candle_holder_gray", "Gray Candle Holder"},
        {"supplementaries", "candle_holder_green", "Green Candle Holder"},
        {"supplementaries", "candle_holder_light_blue", "Light Blue Candle Holder"},
        {"supplementaries", "candle_holder_light_gray", "Light Gray Candle Holder"},
        {"supplementaries", "candle_holder_lime", "Lime Candle Holder"},
        {"supplementaries", "candle_holder_magenta", "Magenta Candle Holder"},
        {"supplementaries", "candle_holder_orange", "Orange Candle Holder"},
        {"supplementaries", "candle_holder_pink", "Pink Candle Holder"},
        {"supplementaries", "candle_holder_purple", "Purple Candle Holder"},
        {"supplementaries", "candle_holder_red", "Red Candle Holder"},
        {"supplementaries", "candle_holder_soul", "Soul Candle Holder"},
        {"supplementaries", "candle_holder_spectacle", "Spectacle Candle Holder"},
        {"supplementaries", "candle_holder_white", "White Candle Holder"},
        {"supplementaries", "candle_holder_yellow", "Yellow Candle Holder"},
        {"supplementaries", "cannon", "Cannon"},
        {"supplementaries", "cannonball", "Cannonball"},
        {"supplementaries", "checker_block", "Checker Block"},
        {"supplementaries", "checker_slab", "Checker Slab"},
        {"supplementaries", "clock_block", "Clock Block"},
        {"supplementaries", "cog_block", "Cog Block"},
        {"supplementaries", "crank", "Crank"},
        {"supplementaries", "crystal_display", "Crystal Display"},
        {"supplementaries", "daub", "Daub"},
        {"supplementaries", "daub_brace", "Wattle and Daub Brace"},
        {"supplementaries", "daub_cross_brace", "Wattle and Daub Cross Brace"},
        {"supplementaries", "daub_frame", "Wattle and Daub Frame"},
        {"supplementaries", "deepslate_lamp", "Deepslate Lamp"},
        {"supplementaries", "doormat", "Doormat"},
        {"supplementaries", "end_stone_lamp", "End Stone Lamp"},
        {"supplementaries", "enderman_head", "Enderman Head"},
        {"supplementaries", "enderman_wall_head", "Wall Enderman Head"},
        {"supplementaries", "faucet", "Faucet"},
        {"supplementaries", "feather_block", "Feather Block"},
        {"supplementaries", "fine_wood", "Fine Wood"},
        {"supplementaries", "fine_wood_slab", "Fine Wood Slab"},
        {"supplementaries", "fine_wood_stairs", "Fine Wood Stairs"},
        {"supplementaries", "fire_pit", "Fire Pit"},
        {"supplementaries", "flag_black", "Black Flag"},
        {"supplementaries", "flag_blue", "Blue Flag"},
        {"supplementaries", "flag_brown", "Brown Flag"},
        {"supplementaries", "flag_cyan", "Cyan Flag"},
        {"supplementaries", "flag_gray", "Gray Flag"},
        {"supplementaries", "flag_green", "Green Flag"},
        {"supplementaries", "flag_light_blue", "Light Blue Flag"},
        {"supplementaries", "flag_light_gray", "Light Gray Flag"},
        {"supplementaries", "flag_lime", "Lime Flag"},
        {"supplementaries", "flag_magenta", "Magenta Flag"},
        {"supplementaries", "flag_orange", "Orange Flag"},
        {"supplementaries", "flag_pink", "Pink Flag"},
        {"supplementaries", "flag_purple", "Purple Flag"},
        {"supplementaries", "flag_red", "Red Flag"},
        {"supplementaries", "flag_white", "White Flag"},
        {"supplementaries", "flag_yellow", "Yellow Flag"},
        {"supplementaries", "flax", "Flax"},
        {"supplementaries", "flax_block", "Flax Bale"},
        {"supplementaries", "flint_block", "Block of Flint"},
        {"supplementaries", "flower_box", "Flower Box"},
        {"supplementaries", "fodder", "Fodder"},
        {"supplementaries", "globe", "Globe"},
        {"supplementaries", "globe_sepia", "Sepia Globe"},
        {"supplementaries", "goblet", "Goblet"},
        {"supplementaries", "gold_bars", "Gold Bars"},
        {"supplementaries", "gold_door", "Gold Door"},
        {"supplementaries", "gold_gate", "Gold Gate"},
        {"supplementaries", "gold_trapdoor", "Gold Trapdoor"},
        {"supplementaries", "gravel_bricks", "Gravel Bricks"},
        {"supplementaries", "gunpowder", "Gunpowder"},
        {"supplementaries", "hourglass", "Hourglass"},
        {"supplementaries", "iron_gate", "Iron Gate"},
        {"supplementaries", "item_shelf", "Item Shelf"},
        {"supplementaries", "jar", "Jar"},
        {"supplementaries", "jar_boat", "Boat in a Jar"},
        {"supplementaries", "jar_tinted", "Tinted Jar"},
        {"supplementaries", "lapis_bricks", "Lapis Bricks"},
        {"supplementaries", "lapis_bricks_slab", "Lapis Brick Slab"},
        {"supplementaries", "lapis_bricks_stairs", "Lapis Brick Stairs"},
        {"supplementaries", "lapis_bricks_wall", "Lapis Brick Wall"},
        {"supplementaries", "lock_block", "Lock Block"},
        {"supplementaries", "lumisene", "Lumisene"},
        {"supplementaries", "lunch_basket", "Lunch Basket"},
        {"supplementaries", "mob_jar", "Mob Jar"},
        {"supplementaries", "netherite_door", "Netherite Door"},
        {"supplementaries", "netherite_trapdoor", "Netherite Trapdoor"},
        {"supplementaries", "notice_board", "Notice Board"},
        {"supplementaries", "pancake", "Pancake"},
        {"supplementaries", "pedestal", "Pedestal"},
        {"supplementaries", "planter", "Planter"},
        {"supplementaries", "potted_flax", "Potted Flax"},
        {"supplementaries", "present", "Present"},
        {"supplementaries", "present_black", "Black Present"},
        {"supplementaries", "present_blue", "Blue Present"},
        {"supplementaries", "present_brown", "Brown Present"},
        {"supplementaries", "present_cyan", "Cyan Present"},
        {"supplementaries", "present_gray", "Gray Present"},
        {"supplementaries", "present_green", "Green Present"},
        {"supplementaries", "present_light_blue", "Light Blue Present"},
        {"supplementaries", "present_light_gray", "Light Gray Present"},
        {"supplementaries", "present_lime", "Lime Present"},
        {"supplementaries", "present_magenta", "Magenta Present"},
        {"supplementaries", "present_orange", "Orange Present"},
        {"supplementaries", "present_pink", "Pink Present"},
        {"supplementaries", "present_purple", "Purple Present"},
        {"supplementaries", "present_red", "Red Present"},
        {"supplementaries", "present_white", "White Present"},
        {"supplementaries", "present_yellow", "Yellow Present"},
        {"supplementaries", "prismarine_rod", "Prismarine Rod"},
        {"supplementaries", "raked_gravel", "Raked Gravel"},
        {"supplementaries", "redstone_illuminator", "Redstone Illuminator"},
        {"supplementaries", "relayer", "Relayer"},
        {"supplementaries", "rope", "Rope"},
        {"supplementaries", "rope_chandelier", "Rope Chandelier"},
        {"supplementaries", "rope_ender_chandelier", "Ender Rope Chandelier"},
        {"supplementaries", "rope_glow_chandelier", "Glow Rope Chandelier"},
        {"supplementaries", "rope_knot", "Roped Post"},
        {"supplementaries", "rope_soul_chandelier", "Soul Rope Chandelier"},
        {"supplementaries", "sack", "Sack"},
        {"supplementaries", "safe", "Safe"},
        {"supplementaries", "sconce", "Sconce"},
        {"supplementaries", "sconce_ender", "Ender Sconce"},
        {"supplementaries", "sconce_glow", "Glowlight Sconce"},
        {"supplementaries", "sconce_green", "Cupric Sconce"},
        {"supplementaries", "sconce_lever", "Sconce Lever"},
        {"supplementaries", "sconce_nether_brass", "Nether Brass Sconce"},
        {"supplementaries", "sconce_soul", "Soul Sconce"},
        {"supplementaries", "sconce_wall", "Sconce"},
        {"supplementaries", "sconce_wall_ender", "Ender Sconce"},
        {"supplementaries", "sconce_wall_glow", "Glowlight Sconce"},
        {"supplementaries", "sconce_wall_green", "Cupric Sconce"},
        {"supplementaries", "sconce_wall_nether_brass", "Nether Brass Sconce"},
        {"supplementaries", "sconce_wall_soul", "Soul Sconce"},
        {"supplementaries", "slidy_block", "Sliding Block"},
        {"supplementaries", "soap_block", "Soap Block"},
        {"supplementaries", "soul_jar", "Soul Jar"},
        {"supplementaries", "speaker_block", "Speaker Block"},
        {"supplementaries", "spider_head", "Spider Head"},
        {"supplementaries", "spider_wall_head", "Wall Spider Head"},
        {"supplementaries", "spring_launcher_arm", "Spring Launcher Arm"},
        {"supplementaries", "spring_launcher_head", "Spring Launcher"},
        {"supplementaries", "statue", "Statue"},
        {"supplementaries", "stick", "Stick"},
        {"supplementaries", "stone_lamp", "Stone Lamp"},
        {"supplementaries", "stone_tile", "Stone Tiles"},
        {"supplementaries", "stone_tile_slab", "Stone Tile Slab"},
        {"supplementaries", "stone_tile_stairs", "Stone Tile Stairs"},
        {"supplementaries", "stone_tile_wall", "Stone Tile Wall"},
        {"supplementaries", "sugar_cube", "Sugar Cube"},
        {"supplementaries", "suspicious_gravel_bricks", "Suspicious Gravel Bricks"},
        {"supplementaries", "tater_in_a_jar", "Tater in a Jar"},
        {"supplementaries", "timber_brace", "Timber Brace"},
        {"supplementaries", "timber_cross_brace", "Timber Cross Brace"},
        {"supplementaries", "timber_frame", "Timber Frame"},
        {"supplementaries", "trapped_present", "Trapped Present"},
        {"supplementaries", "trapped_present_black", "Trapped Black Present"},
        {"supplementaries", "trapped_present_blue", "Trapped Blue Present"},
        {"supplementaries", "trapped_present_brown", "Trapped Brown Present"},
        {"supplementaries", "trapped_present_cyan", "Trapped Cyan Present"},
        {"supplementaries", "trapped_present_gray", "Trapped Gray Present"},
        {"supplementaries", "trapped_present_green", "Trapped Green Present"},
        {"supplementaries", "trapped_present_light_blue", "Trapped Light Blue Present"},
        {"supplementaries", "trapped_present_light_gray", "Trapped Light Gray Present"},
        {"supplementaries", "trapped_present_lime", "Trapped Lime Present"},
        {"supplementaries", "trapped_present_magenta", "Trapped Magenta Present"},
        {"supplementaries", "trapped_present_orange", "Trapped Orange Present"},
        {"supplementaries", "trapped_present_pink", "Trapped Pink Present"},
        {"supplementaries", "trapped_present_purple", "Trapped Purple Present"},
        {"supplementaries", "trapped_present_red", "Trapped Red Present"},
        {"supplementaries", "trapped_present_white", "Trapped White Present"},
        {"supplementaries", "trapped_present_yellow", "Trapped Yellow Present"},
        {"supplementaries", "turn_table", "Turn Table"},
        {"supplementaries", "urn", "Urn"},
        {"supplementaries", "way_sign", "Way Sign"},
        {"supplementaries", "way_sign_wall", "Wall Way Sign"},
        {"supplementaries", "wicker_fence", "Wicker Fence"},
        {"supplementaries", "wild_flax", "Wild Flax"},
        {"supplementaries", "wind_vane", "Wind Vane"},
        {"amendments", "carpet_slab", "Carpet Slab"},
        {"amendments", "carpet_stairs", "Carpet Stairs"},
        {"amendments", "ceiling_banner_black", "Black Ceiling Banner"},
        {"amendments", "ceiling_banner_blue", "Blue Ceiling Banner"},
        {"amendments", "ceiling_banner_brown", "Brown Ceiling Banner"},
        {"amendments", "ceiling_banner_cyan", "Cyan Ceiling Banner"},
        {"amendments", "ceiling_banner_gray", "Gray Ceiling Banner"},
        {"amendments", "ceiling_banner_green", "Green Ceiling Banner"},
        {"amendments", "ceiling_banner_light_blue", "Light Blue Ceiling Banner"},
        {"amendments", "ceiling_banner_light_gray", "Light Gray Ceiling Banner"},
        {"amendments", "ceiling_banner_lime", "Lime Ceiling Banner"},
        {"amendments", "ceiling_banner_magenta", "Magenta Ceiling Banner"},
        {"amendments", "ceiling_banner_orange", "Orange Ceiling Banner"},
        {"amendments", "ceiling_banner_pink", "Pink Ceiling Banner"},
        {"amendments", "ceiling_banner_purple", "Purple Ceiling Banner"},
        {"amendments", "ceiling_banner_red", "Red Ceiling Banner"},
        {"amendments", "ceiling_banner_white", "White Ceiling Banner"},
        {"amendments", "ceiling_banner_yellow", "Yellow Ceiling Banner"},
        {"amendments", "directional_cake", "Directional Cake"},
        {"amendments", "double_cake", "Double Cake"},
        {"amendments", "dye_cauldron", "Dye Cauldron"},
        {"amendments", "hanging_flower_pot", "Hanging Flower Pot"},
        {"amendments", "liquid_cauldron", "Liquid Cauldron"},
        {"amendments", "skull_candle", "Skull Candle"},
        {"amendments", "skull_candle_soul", "Soul Skull Candle"},
        {"amendments", "skull_candle_soul_wall", "Wall Soul Skull Candle"},
        {"amendments", "skull_candle_wall", "Wall Skull Candle"},
        {"amendments", "skull_pile", "Skull Pile"},
        {"amendments", "tool_hook", "Tool Hook"},
        {"amendments", "wall_lantern", "Wall Lantern"},
        {"amendments", "wall_soul_lantern", "Wall Soul Lantern"},
    };
    public static void register(PonderSceneRegistrationHelper<ItemLike> helper,
                                          ResourceLocation tagAe2, ResourceLocation tagSupp, ResourceLocation tagAmend) {
        java.util.Set<ItemLike> claimed = new java.util.HashSet<>();
        for (String[] b : BLOCKS) {
            ItemLike item = MatsPonderPlugin.item(b[0] + ":" + b[1]);
            if (item == null) continue;
            if (!claimed.add(item)) continue;
            final String sceneId = "auto_" + b[0] + "_" + b[1].replaceAll("[^a-zA-Z0-9_]", "_");
            final String enName = b[2];
            final boolean ae2 = "ae2".equals(b[0]);
            final ResourceLocation tag = ae2 ? tagAe2 : ("amendments".equals(b[0]) ? tagAmend : tagSupp);
            helper.addStoryBoard(item, sceneId, (scene, util) -> generic(scene, util, sceneId, enName, ae2), tag);
        }
    }
    private static void generic(SceneBuilder scene, SceneBuildingUtil util, String sceneId, String enName, boolean ae2) {
        scene.title(sceneId, enName);
        scene.setNextUpEnabled(false);
        scene.configureBasePlate(0, 0, 5);
        scene.showBasePlate();
        scene.idle(10);
        BlockPos pos = util.grid().at(2, 1, 2);
        scene.world().showSection(util.select().position(pos), Direction.DOWN);
        scene.idle(15);
        scene.overlay().showText(90).text("matsponder.ponder." + sceneId + ".text_1")
            .placeNearTarget().attachKeyFrame().pointAt(util.vector().centerOf(pos));
        scene.idle(100);
        scene.overlay().showText(110).text("matsponder.ponder." + sceneId + ".text_2")
            .placeNearTarget().attachKeyFrame().pointAt(util.vector().topOf(pos));
        scene.idle(120);
    }
}